version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend
    networks:
      - docker-project
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: ['npm', 'start']

  backend:
    build: ./backend
    ports:
      - '4000:4000'
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://agustin:hola1234@db:5432/docker_project_db
    networks:
      - docker-project
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: ['npm', 'run', 'dev']

  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: agustin
      POSTGRES_PASSWORD: hola1234
      POSTGRES_DB: docker_project_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - docker-project

volumes:
  postgres_data:

networks:
  docker-project:
    driver: bridge
